default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres@123
  host: localhost

development:
  <<: *default
  database: weather_app_development

test:
  <<: *default
  database: weather_app_test

production:
  <<: *default
  database: weather_app_production
  username: weather_app
  password: <%= ENV["WEATHER_APP_DATABASE_PASSWORD"] %>
